### ISSUE TITLE
Compatibility with the Cmake system in newer esp-idf.

### ISSUE THREAD

**Issue by UtkarshBhatthere** [natanaeljr/esp32-MPU-driver#11]
The library is not compatible with the CMake based build system. I being new to CMake am pretty unsure of what's happening. Could you please tweak the library to work with the new system?

**Comment by souryavarenya** [comment]
I created CMakeLists.txt file for all three libraries but they're not showing up in the configuration menu. I will fork and pull once it works. 

@natanaeljr Any Idea why this could be happening?

**Comment by UtkarshBhatthere** [comment]
@natanaeljr any updates with the cmake inclusion ?

**Comment by natanaeljr** [comment]
Yes, the library is now compatible with CMake build system. Added in pull request [#12](https://github.com/natanaeljr/esp32-MPU-driver/pull/12).
