### ISSUE TITLE
MPU.hpp library probelm

### ISSUE THREAD

**Issue by jonathanflores891** [natanaeljr/esp32-MPU-driver#15]
Hi! first of all thank you for your work! I've having problems trying to run the examples with the i2c peripheral. It doesn't find the I2Cbus.hpp neither the MPU.hpp even though I clone those libraries in the include directory. Thank you for your time!

"MPUdriver/include/MPU.hpp:34:2: error: #error ''MPU component requires I2Cbus library. Make sure the I2Cbus library is included in your components directory. See MPUs README.md for more information.''
 #error ''MPU component requires I2Cbus library"

**Comment by mauguzz** [comment]
I have the same issue

**Comment by mauguzz** [comment]
> I have the same issue

In my case I'm working on PlatformioIO, and I solved this adding `REQUIRES "I2Cbus"` - to the function `idf_component_register()` on CMakeLists.txt on the /src directory of my project.
