### ISSUE TITLE
Cannot read data.

### ISSUE THREAD

**Issue by 0x0c** [natanaeljr/esp32-MPU-driver#8]
Hi, I'm using this library with MPU9255.

I cannot read data from the sensor when I call `MPU.acceleration` in FreeRTOS task.
There are some errors at the console like this.

```
E (155274) I2Cbus: [port:0, slave:0x68] Failed to read 6 bytes from register 0x3B, error: 0x107
```

I can get a data without using FreeRTOS task.
How to avoid this issue?

I'm using esp-idf v3.1 and MPU9250.

Regards,
Akira

**Comment by 0x0c** [comment]
Sorry, I resolve this issue so I close this. Thank you.

**Comment by esperancaleonardo** [comment]
How did you solve this guy??? I'm stuck at the same error.....
